### ISSUE TITLE
Undgå nyt login efter hver registrering

### ISSUE THREAD

**Issue by baffioso** [ballerupgis/bilreg#1]
Når formular data sendes genindlæses siden, hvilket betyder at API key bliver slettet, hvilket kræver ny login inden næste indberetning. Ville det være muligt at tømme formularen i stedet for https://github.com/ballerupgis/bilreg/blob/4efb66a92b2eff2c0682728836e56d5e90d2a88b/main.js#L223

**Comment by nixen97** [comment]
God ide. Lad os gøre det.

**Comment by baffioso** [comment]
Check
