### ISSUE TITLE
Login-logikken virker ikke i Internet Explorer

### ISSUE THREAD

**Issue by nixen97** [ballerupgis/bilreg#5]

**Comment by baffioso** [comment]
Brænd i helvede EI

**Comment by nixen97** [comment]
Ikke uenig ;)
Opdaget det kun fordi Mads tilgik det via IE

**Comment by nixen97** [comment]
Men jeg tror jeg har fundet problemet

**Comment by baffioso** [comment]
Fedt. Ellers må han bruge chrome

**Comment by nixen97** [comment]
"Fixed" ved at tilføje en fejl-meddelelse til IE
